CREATE TABLE APPLICANT(NAME VARCHAR(20),AGE INT,SEX VARCHAR(20),EDUCATION VARCHAR(20),EXTRA VARCHAR(20),SALARY INT,FIELD INT,LOGIN VARCHAR(20),PWD VARCHAR(20)); 
INSERT INTO APPLICANT VALUES('RAY',20,'male','degree','c',15000,1,'ray','dah');
SELECT * FROM APPLICANT;

CREATE TABLE COMPANY(NAME VARCHAR(20),VACANCY VARCHAR(20),SALARY INT,FIELD INT,LOGIN VARCHAR(20),PWD VARCHAR(20)); 
INSERT INTO COMPANY VALUES('INFY','SOFTWARE DEV',15000,1,'INFY','MYINFY');
SELECT * FROM COMPANY;
USE GO;

DROP TABLE APPLICANT
CREATE TABLE APPLICANT(NAME VARCHAR(20),AGE INT,SEX VARCHAR(20),EDUCATION VARCHAR(20),EXTRA VARCHAR(20),SALARY VARCHAR(40),FIELD INT,LOGIN VARCHAR(20),PWD VARCHAR(20)); 
INSERT INTO APPLICANT VALUES('RAY',20,'male','degree','c',15000,1,'ray','dah');
SELECT * FROM APPLICANT;
DROP TABLE COMPANY


CREATE TABLE COMPANY(NAME VARCHAR(20),VACANCY VARCHAR(20),SALARY VARCHAR(20),FIELD VARCHAR(20),LOGIN VARCHAR(20),PWD VARCHAR(20)); 
INSERT INTO COMPANY VALUES('INFY','SOFTWARE DEV',15000,1,'INFY','MYINFY');
SELECT * FROM COMPANY;